name: cinescope
description: "A modern IMDb clone built with Flutter and BloC state management to explore movies and TV shows effortlessly."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Architecture
  flutter_bloc: ^8.1.6

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Navigation
  go_router: ^14.6.0

  # Networking
  http: ^1.2.2
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_secure_storage: ^4.2.1

  # Utils
  logging: ^1.3.0
  equatable: ^2.0.6
  flutter_dotenv: ^5.2.1

  # Images and Files
  flutter_svg: ^2.0.15

  # Localization
  cine_scope_localization:
    path: packages/cine_scope_localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1

  thunder_analysis:
    git:
      url: https://github.com/khamidjon/thunder-analysis
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

